[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
shadow_ranch_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
shadow_ranch_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/christophercialone/Desktop/Desktop/my_solana_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/shadow-ranch-program"]

[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.22"

[build]
cargo_build_command = "cargo-build-sbf"

[test.validator]
# Security: Configure test validator with proper settings
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
bind_address = "127.0.0.1"
rpc_port = 8899
websocket_url = "ws://127.0.0.1:8900/"


